server:
  port: 1002
  servlet.context-path: /product-register # It is the root Uri eg: http://localhost:1001/customer-register/customer/addCustomer

spring:
  application:
    name: product-application
  datasource:
    #Postgres Database
    url: jdbc:postgresql://192.168.0.100:5432/postgres
    username: postgres
    password: 123456789
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    properties.format_sql: true
    properties.show-sql: true