apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: order-deployment
  labels:
    app: orderlabel
spec:
  replicas: 1 # Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: orderlabel
  template:
    metadata:
      labels:
        app: orderlabel
    spec:
      containers:
        - name: spring-boot-order-service
          image: spring-boot-order-service:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1003 # The port that the container is running on in the cluster